# Generated by Django 3.2 on 2021-06-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210617_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='ceAP',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceAQ',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceBP',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceBQ',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceCHNG',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceCOI',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceIV',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceLTP',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceOI',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='ceV',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='globalceTOTOI',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='globalceTOVOI',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='globalpeTOTOI',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='globalpeTOVOI',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peAP',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peAQ',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peBP',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peBQ',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peCHNG',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peCOI',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peIV',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peLTP',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peOI',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='peV',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='strikePrice',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11),
        ),
    ]
