# Generated by Django 3.2 on 2021-06-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210617_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceAP',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceAQ',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceBP',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceBQ',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceCHNG',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceCOI',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceIV',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceLTP',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceOI',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='ceV',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='globalceTOTOI',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='globalceTOVOI',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='globalpeTOTOI',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='globalpeTOVOI',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peAP',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peAQ',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peBP',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peBQ',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peCHNG',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peCOI',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peIV',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peLTP',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peOI',
        ),
        migrations.RemoveField(
            model_name='stockmarket',
            name='peV',
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='CEtotOI',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='CEtotVoi',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='PEtotOI',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='PEtotVoi',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='ceaskPrice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='ceaskQty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='cebidQty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='cebidprice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='cechange',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='cechangeinOpenInterest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='ceimpliedVolatility',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='celastPrice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='ceopenInterest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='cetotalTradedVolume',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='peaskPrice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='peaskQty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='pebidQty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='pebidprice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='pechange',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='pechangeinOpenInterest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='peimpliedVolatility',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='pelastPrice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='peopenInterest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='petotalTradedVolume',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='strikePrice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11),
        ),
    ]
